# Generated by Django 4.2.7 on 2023-11-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INFO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yourmodel',
            table='User_table',
        ),
    ]
