# Generated by Django 4.2.7 on 2023-11-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INFO', '0003_alter_yourmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yourmodel',
            table='User_table',
        ),
    ]
