# Generated by Django 4.2.7 on 2023-11-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INFO', '0005_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
