# Generated by Django 4.2.7 on 2023-11-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INFO', '0006_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
